version: "3.8"

services:
  app1:
    build: ./app1
    container_name: app1
    expose:
      - 5000

  app2:
    build: ./app2
    container_name: app2
    expose:
      - 5000

  nginx:
    image: nginx:alpine
    container_name: reverse-proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
